
# Site settings
title: Changhe Xie
name: Changhe Xie
subtitle: Creator
email: xietheus@gmail.com
description: >
   Creator
baseurl: ""
url: "https://nonnature.github.io/"
github_username:  nonnature
disqus_baseurl: "https://nonnature.github.io/"
disqus_shortname: https-nonnature-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Changhe Xie"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: nonnature
    url: https://github.com/nonnature
    desc: See more projects on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Changhe Xie
    url: https://www.linkedin.com/in/changhe-xie-182698268/
    desc: Check my LinkedIn
    share: true
